### ISSUE TITLE
css tips - 记录平时遇到的css小问题

### ISSUE THREAD

**Issue by tomwang1013** [tomwang1013/gists#8]
1. css属性inherit，initial，unset的区别：
https://www.quirksmode.org/css/cascading/values.html

2. css shorthand写法中遗漏的属性的值都是initial值

3. css属性继承：
https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Cascade_and_inheritance

从大的方面：
Importance > Specificity > source order

importance:
user!important > author!important > author normal > user normal > user agent default

大的方面决定不了之后，再看Specificity；Specificity再决定不了，最后看source order

**Comment by tomwang1013** [comment]
4. 定位元素的大小和位置是相对于最近的定位祖先元素而言的（如果没有，则是body元素），而不是其直接父元素的，所以请设置其父元素为relative；另外，设置left和right属性可以间接地设置其width

**Comment by tomwang1013** [comment]
5. inline VS inline-block
**inline**可以设置的属性：border, margin-left/right, padding-left/right. width, height, margin-top/bottom直接忽略，但是padding-top/bottom会有影响：
![image](https://user-images.githubusercontent.com/1826003/29115584-bb5ec292-7d2a-11e7-85b5-d4f4f697d9b8.png)
**不能在上下方向撑开空白！**
```css
.test { 
    display: inline; 
    height: 100px; 
    border: dotted 1px red; 
    background-color: red; 
    padding: 10px 20px; 
    margin: 20px 20px;
}
```

**inline-block**所有熟悉都能设置：
![image](https://user-images.githubusercontent.com/1826003/29115706-22283b0c-7d2b-11e7-9179-95658a516e08.png)
```css
.test { 
    display: inline-block; 
    height: 100px; 
    border: dotted 1px red; 
    background-color: red; 
    padding: 10px 20px; 
    margin: 20px 20px;
}
```

**Comment by tomwang1013** [comment]
**6. transform中scale和translate的顺序问题**

如果同时在transform中指定scale和translate，它们的顺序是很重要的，下面2种写法效果完全不同：

```css
transform: scale(0.5) translate(40px, 50px);  
transform: translate(40px, 50px)  scale(0.5);
```

想要元素移动指定的距离的话必须采用第二种写法：也就是先移动再缩放；第一种写法的话，后面的移动距离也会受scale因子的影响

**Comment by tomwang1013** [comment]
## 7. user-select: none会阻止浏览器的默认滚动行为

默认情况下，当出现滚动条时，鼠标按住拖动经过时滚动条会自动滚动以展示隐藏的内容。但是如果我们组织了文本选中：`user-select: none`，就把这个默认行为也阻止了，这时候浏览器不会自动滚动。

如果你不想看到文本的选中效果可以这样做：

```css
/*Webkit,Opera9.5+,Ie9+*/
::selection {
  background: transparent;
}
/*Mozilla Firefox*/
::-moz-selection {
  background: transparent;
}
```

把选中文本的背景色置为透明
